### PR TITLE
ci: integrate fossa

### LINKED ISSUE #53: [EP] update FOSSA integration
## Describe the problem

The FOSSA integration is currently broken and the analysis is not executed during PR and merge.
I updated the authorization for material-identity and that was the occasion to dig into their docs.
It seems like there is a more efficient way to run the analysis than by using webhooks and since the analysis was always rather slow it got my attention.
So i suggest that we integrate this new process.

## Specify the details

See https://docs.fossa.com/docs/provided-builds

## Explain the benefits

See https://docs.fossa.com/docs/provided-builds#pros

### PR DESCRIPTION
**Pull request by getlarge**
# Description

Fixes #53 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by stiebitzhofer** [comment]
This looks very good except one point: if I go to https://app.fossa.com/projects/custom%2B18065%2Fgithub.com%2Fmaterial-identity%2FCoA-schemas/refs/branch/ci-integrate-fossa/4053638a54389e9986e49cb9bab38bb4bce5f497/export I would expect a full report on the licenses. Is this a misconfiguration or something which doesn't work anymore? Where would I get a report?

Bildschirmfoto 2023-04-11 um 12 06 57

**Comment by getlarge** [comment]
> This looks very good except one point: if I go to https://app.fossa.com/projects/custom%2B18065%2Fgithub.com%2Fmaterial-identity%2FCoA-schemas/refs/branch/ci-integrate-fossa/4053638a54389e9986e49cb9bab38bb4bce5f497/export I would expect a full report on the licenses. Is this a misconfiguration or something which doesn't work anymore? Where would I get a report?
> 
> Bildschirmfoto 2023-04-11 um 12 06 57

I don't know what's the issue on your end, if you check the video below you'll se that this link led me to the report page:

https://user-images.githubusercontent.com/15331923/231136307-a110c0b8-1d2f-4ec6-9c16-f14bb7038b0c.mov

Can't you access the report by clicking the `Reports` tab in the project view ?

**Comment by getlarge** [comment]
> This looks very good except one point: if I go to https://app.fossa.com/projects/custom%2B18065%2Fgithub.com%2Fmaterial-identity%2FCoA-schemas/refs/branch/ci-integrate-fossa/4053638a54389e9986e49cb9bab38bb4bce5f497/export I would expect a full report on the licenses. Is this a misconfiguration or something which doesn't work anymore? Where would I get a report?
> 
Now i get it, you meant that there are no dependencies listed in the report ?
Indeed that's strange and that only applies to the repositories in material identity org.
I'll try to find out why.

**Comment by getlarge** [comment]
@stiebitzhofer i found out why, FOSSA analysis ignores the `devDependencies` in package.json, which makes sense as they are not (supposed to be) shipped in the bundle.
See https://docs.fossa.com/docs/javascript#repository-scanning.
The only exception is for the code in the `generate-pdf.min.js` which has some external libs bundled into it.
So i added `@s1seven/schema-tools-generate-en10168-pdf-template` in the dependencies (from which `generate-pdf.min.js` originates) so that it can be scanned by FOSSA.

**Comment by stiebitzhofer** [comment]
Yes

**Pull request merged**
